# Generated by Django 5.0.3 on 2024-03-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='farms',
            field=models.ManyToManyField(blank=True, related_name='authorities', to='agri.farmer'),
        ),
    ]
